name: build-push-and-deploy-spa

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    env:
      REGION: us-central1
      PROJECT_ID: payway-472402
      SPA_BUCKET: website-payway-bz
      # SPA_PREFIX: ""

    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:
      - name: Set APP_DIR env
        run: echo "APP_DIR=workspace/apps/$(basename "$GITHUB_REPOSITORY")" >> "$GITHUB_ENV"

      - name: Checkout workspace repo
        uses: actions/checkout@v4
        with:
          repository: payway-bz/workspace
          path: workspace
          fetch-depth: 1

      - name: Checkout current repo into workspace/apps/<repo>
        uses: actions/checkout@v4
        with:
          path: ${{ env.APP_DIR }}
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build docker image
        working-directory: ${{ env.APP_DIR }}
        run: ../../helpers/docker-build

      - name: Export dist from Docker build (BuildKit local exporter)
        working-directory: ${{ env.APP_DIR }}
        run: |
          rm -rf out
          docker buildx build \
            --target export \
            --output type=local,dest=out \
            .

      - name: Upload SPA bundle to GCS
        uses: google-github-actions/upload-cloud-storage@v3
        with:
          path: ${{ env.APP_DIR }}/out/dist
          destination: ${{ env.SPA_BUCKET }}${{ env.SPA_PREFIX && format('/{0}', env.SPA_PREFIX) }}
          parent: false  # upload contents of dist-out to the prefix root
